# ruff: noqa: E501
from .models import SurahModel

SURAHS: list[SurahModel] = [
    SurahModel(
        id=1,
        name_arabic="الفاتحة",
        name_translit="Al-Fatiha",
        name_translation="The Opening",
        revelation_type="meccan",
        ayah_count=7,
        order_number=1,
    ),
    SurahModel(
        id=2,
        name_arabic="البقرة",
        name_translit="Al-Baqara",
        name_translation="The Cow",
        revelation_type="medinan",
        ayah_count=286,
        order_number=2,
    ),
    SurahModel(
        id=3,
        name_arabic="آل عمران",
        name_translit="Aal-Imran",
        name_translation="Family of Imran",
        revelation_type="medinan",
        ayah_count=200,
        order_number=3,
    ),
    SurahModel(
        id=4,
        name_arabic="النساء",
        name_translit="An-Nisa",
        name_translation="The Women",
        revelation_type="medinan",
        ayah_count=176,
        order_number=4,
    ),
    SurahModel(
        id=5,
        name_arabic="المائدة",
        name_translit="Al-Maidah",
        name_translation="The Table Spread",
        revelation_type="medinan",
        ayah_count=120,
        order_number=5,
    ),
    SurahModel(
        id=6,
        name_arabic="الأنعام",
        name_translit="Al-Anam",
        name_translation="The Cattle",
        revelation_type="meccan",
        ayah_count=165,
        order_number=6,
    ),
    SurahModel(
        id=7,
        name_arabic="الأعراف",
        name_translit="Al-Araf",
        name_translation="The Heights",
        revelation_type="meccan",
        ayah_count=206,
        order_number=7,
    ),
    SurahModel(
        id=8,
        name_arabic="الأنفال",
        name_translit="Al-Anfal",
        name_translation="The Spoils of War",
        revelation_type="medinan",
        ayah_count=75,
        order_number=8,
    ),
    SurahModel(
        id=9,
        name_arabic="التوبة",
        name_translit="At-Tawbah",
        name_translation="The Repentance",
        revelation_type="medinan",
        ayah_count=129,
        order_number=9,
    ),
    SurahModel(
        id=10,
        name_arabic="يونس",
        name_translit="Yunus",
        name_translation="Jonah",
        revelation_type="meccan",
        ayah_count=109,
        order_number=10,
    ),
    SurahModel(
        id=11,
        name_arabic="هود",
        name_translit="Hud",
        name_translation="Hud",
        revelation_type="meccan",
        ayah_count=123,
        order_number=11,
    ),
    SurahModel(
        id=12,
        name_arabic="يوسف",
        name_translit="Yusuf",
        name_translation="Joseph",
        revelation_type="meccan",
        ayah_count=111,
        order_number=12,
    ),
    SurahModel(
        id=13,
        name_arabic="الرعد",
        name_translit="Ar-Rad",
        name_translation="The Thunder",
        revelation_type="medinan",
        ayah_count=43,
        order_number=13,
    ),
    SurahModel(
        id=14,
        name_arabic="إبراهيم",
        name_translit="Ibrahim",
        name_translation="Abraham",
        revelation_type="meccan",
        ayah_count=52,
        order_number=14,
    ),
    SurahModel(
        id=15,
        name_arabic="الحجر",
        name_translit="Al-Hijr",
        name_translation="The Rocky Tract",
        revelation_type="meccan",
        ayah_count=99,
        order_number=15,
    ),
    SurahModel(
        id=16,
        name_arabic="النحل",
        name_translit="An-Nahl",
        name_translation="The Bee",
        revelation_type="meccan",
        ayah_count=128,
        order_number=16,
    ),
    SurahModel(
        id=17,
        name_arabic="الإسراء",
        name_translit="Al-Isra",
        name_translation="The Night Journey",
        revelation_type="meccan",
        ayah_count=111,
        order_number=17,
    ),
    SurahModel(
        id=18,
        name_arabic="الكهف",
        name_translit="Al-Kahf",
        name_translation="The Cave",
        revelation_type="meccan",
        ayah_count=110,
        order_number=18,
    ),
    SurahModel(
        id=19,
        name_arabic="مريم",
        name_translit="Maryam",
        name_translation="Mary",
        revelation_type="meccan",
        ayah_count=98,
        order_number=19,
    ),
    SurahModel(
        id=20,
        name_arabic="طه",
        name_translit="Ta-Ha",
        name_translation="Ta-Ha",
        revelation_type="meccan",
        ayah_count=135,
        order_number=20,
    ),
    SurahModel(
        id=21,
        name_arabic="الأنبياء",
        name_translit="Al-Anbiya",
        name_translation="The Prophets",
        revelation_type="meccan",
        ayah_count=112,
        order_number=21,
    ),
    SurahModel(
        id=22,
        name_arabic="الحج",
        name_translit="Al-Hajj",
        name_translation="The Pilgrimage",
        revelation_type="medinan",
        ayah_count=78,
        order_number=22,
    ),
    SurahModel(
        id=23,
        name_arabic="المؤمنون",
        name_translit="Al-Muminun",
        name_translation="The Believers",
        revelation_type="meccan",
        ayah_count=118,
        order_number=23,
    ),
    SurahModel(
        id=24,
        name_arabic="النور",
        name_translit="An-Nur",
        name_translation="The Light",
        revelation_type="medinan",
        ayah_count=64,
        order_number=24,
    ),
    SurahModel(
        id=25,
        name_arabic="الفرقان",
        name_translit="Al-Furqan",
        name_translation="The Criterion",
        revelation_type="meccan",
        ayah_count=77,
        order_number=25,
    ),
    SurahModel(
        id=26,
        name_arabic="الشعراء",
        name_translit="Ash-Shuara",
        name_translation="The Poets",
        revelation_type="meccan",
        ayah_count=227,
        order_number=26,
    ),
    SurahModel(
        id=27,
        name_arabic="النمل",
        name_translit="An-Naml",
        name_translation="The Ant",
        revelation_type="meccan",
        ayah_count=93,
        order_number=27,
    ),
    SurahModel(
        id=28,
        name_arabic="القصص",
        name_translit="Al-Qasas",
        name_translation="The Stories",
        revelation_type="meccan",
        ayah_count=88,
        order_number=28,
    ),
    SurahModel(
        id=29,
        name_arabic="العنكبوت",
        name_translit="Al-Ankabut",
        name_translation="The Spider",
        revelation_type="meccan",
        ayah_count=69,
        order_number=29,
    ),
    SurahModel(
        id=30,
        name_arabic="الروم",
        name_translit="Ar-Rum",
        name_translation="The Romans",
        revelation_type="meccan",
        ayah_count=60,
        order_number=30,
    ),
    SurahModel(
        id=31,
        name_arabic="لقمان",
        name_translit="Luqman",
        name_translation="Luqman",
        revelation_type="meccan",
        ayah_count=34,
        order_number=31,
    ),
    SurahModel(
        id=32,
        name_arabic="السجدة",
        name_translit="As-Sajdah",
        name_translation="The Prostration",
        revelation_type="meccan",
        ayah_count=30,
        order_number=32,
    ),
    SurahModel(
        id=33,
        name_arabic="الأحزاب",
        name_translit="Al-Ahzab",
        name_translation="The Combined Forces",
        revelation_type="medinan",
        ayah_count=73,
        order_number=33,
    ),
    SurahModel(
        id=34,
        name_arabic="سبأ",
        name_translit="Saba",
        name_translation="Sheba",
        revelation_type="meccan",
        ayah_count=54,
        order_number=34,
    ),
    SurahModel(
        id=35,
        name_arabic="فاطر",
        name_translit="Fatir",
        name_translation="Originator",
        revelation_type="meccan",
        ayah_count=45,
        order_number=35,
    ),
    SurahModel(
        id=36,
        name_arabic="يس",
        name_translit="Ya-Sin",
        name_translation="Ya Sin",
        revelation_type="meccan",
        ayah_count=83,
        order_number=36,
    ),
    SurahModel(
        id=37,
        name_arabic="الصافات",
        name_translit="As-Saffat",
        name_translation="Those Who Set the Ranks",
        revelation_type="meccan",
        ayah_count=182,
        order_number=37,
    ),
    SurahModel(
        id=38,
        name_arabic="ص",
        name_translit="Sad",
        name_translation="The Letter Sad",
        revelation_type="meccan",
        ayah_count=88,
        order_number=38,
    ),
    SurahModel(
        id=39,
        name_arabic="الزمر",
        name_translit="Az-Zumar",
        name_translation="The Troops",
        revelation_type="meccan",
        ayah_count=75,
        order_number=39,
    ),
    SurahModel(
        id=40,
        name_arabic="غافر",
        name_translit="Ghafir",
        name_translation="The Forgiver",
        revelation_type="meccan",
        ayah_count=85,
        order_number=40,
    ),
    SurahModel(
        id=41,
        name_arabic="فصلت",
        name_translit="Fussilat",
        name_translation="Explained in Detail",
        revelation_type="meccan",
        ayah_count=54,
        order_number=41,
    ),
    SurahModel(
        id=42,
        name_arabic="الشورى",
        name_translit="Ash-Shura",
        name_translation="The Consultation",
        revelation_type="meccan",
        ayah_count=53,
        order_number=42,
    ),
    SurahModel(
        id=43,
        name_arabic="الزخرف",
        name_translit="Az-Zukhruf",
        name_translation="The Ornaments of Gold",
        revelation_type="meccan",
        ayah_count=89,
        order_number=43,
    ),
    SurahModel(
        id=44,
        name_arabic="الدخان",
        name_translit="Ad-Dukhan",
        name_translation="The Smoke",
        revelation_type="meccan",
        ayah_count=59,
        order_number=44,
    ),
    SurahModel(
        id=45,
        name_arabic="الجاثية",
        name_translit="Al-Jathiyah",
        name_translation="The Crouching",
        revelation_type="meccan",
        ayah_count=37,
        order_number=45,
    ),
    SurahModel(
        id=46,
        name_arabic="الأحقاف",
        name_translit="Al-Ahqaf",
        name_translation="The Wind-Curved Sandhills",
        revelation_type="meccan",
        ayah_count=35,
        order_number=46,
    ),
    SurahModel(
        id=47,
        name_arabic="محمد",
        name_translit="Muhammad",
        name_translation="Muhammad",
        revelation_type="medinan",
        ayah_count=38,
        order_number=47,
    ),
    SurahModel(
        id=48,
        name_arabic="الفتح",
        name_translit="Al-Fath",
        name_translation="The Victory",
        revelation_type="medinan",
        ayah_count=29,
        order_number=48,
    ),
    SurahModel(
        id=49,
        name_arabic="الحجرات",
        name_translit="Al-Hujurat",
        name_translation="The Rooms",
        revelation_type="medinan",
        ayah_count=18,
        order_number=49,
    ),
    SurahModel(
        id=50,
        name_arabic="ق",
        name_translit="Qaf",
        name_translation="The Letter Qaf",
        revelation_type="meccan",
        ayah_count=45,
        order_number=50,
    ),
    SurahModel(
        id=51,
        name_arabic="الذاريات",
        name_translit="Adh-Dhariyat",
        name_translation="The Winnowing Winds",
        revelation_type="meccan",
        ayah_count=60,
        order_number=51,
    ),
    SurahModel(
        id=52,
        name_arabic="الطور",
        name_translit="At-Tur",
        name_translation="The Mount",
        revelation_type="meccan",
        ayah_count=49,
        order_number=52,
    ),
    SurahModel(
        id=53,
        name_arabic="النجم",
        name_translit="An-Najm",
        name_translation="The Star",
        revelation_type="meccan",
        ayah_count=62,
        order_number=53,
    ),
    SurahModel(
        id=54,
        name_arabic="القمر",
        name_translit="Al-Qamar",
        name_translation="The Moon",
        revelation_type="meccan",
        ayah_count=55,
        order_number=54,
    ),
    SurahModel(
        id=55,
        name_arabic="الرحمن",
        name_translit="Ar-Rahman",
        name_translation="The Beneficent",
        revelation_type="medinan",
        ayah_count=78,
        order_number=55,
    ),
    SurahModel(
        id=56,
        name_arabic="الواقعة",
        name_translit="Al-Waqiah",
        name_translation="The Inevitable",
        revelation_type="meccan",
        ayah_count=96,
        order_number=56,
    ),
    SurahModel(
        id=57,
        name_arabic="الحديد",
        name_translit="Al-Hadid",
        name_translation="The Iron",
        revelation_type="medinan",
        ayah_count=29,
        order_number=57,
    ),
    SurahModel(
        id=58,
        name_arabic="المجادلة",
        name_translit="Al-Mujadila",
        name_translation="The Pleading Woman",
        revelation_type="medinan",
        ayah_count=22,
        order_number=58,
    ),
    SurahModel(
        id=59,
        name_arabic="الحشر",
        name_translit="Al-Hashr",
        name_translation="The Exile",
        revelation_type="medinan",
        ayah_count=24,
        order_number=59,
    ),
    SurahModel(
        id=60,
        name_arabic="الممتحنة",
        name_translit="Al-Mumtahanah",
        name_translation="She That Is to Be Examined",
        revelation_type="medinan",
        ayah_count=13,
        order_number=60,
    ),
    SurahModel(
        id=61,
        name_arabic="الصف",
        name_translit="As-Saf",
        name_translation="The Ranks",
        revelation_type="medinan",
        ayah_count=14,
        order_number=61,
    ),
    SurahModel(
        id=62,
        name_arabic="الجمعة",
        name_translit="Al-Jumuah",
        name_translation="Friday",
        revelation_type="medinan",
        ayah_count=11,
        order_number=62,
    ),
    SurahModel(
        id=63,
        name_arabic="المنافقون",
        name_translit="Al-Munafiqun",
        name_translation="The Hypocrites",
        revelation_type="medinan",
        ayah_count=11,
        order_number=63,
    ),
    SurahModel(
        id=64,
        name_arabic="التغابن",
        name_translit="At-Taghabun",
        name_translation="Mutual Disillusion",
        revelation_type="medinan",
        ayah_count=18,
        order_number=64,
    ),
    SurahModel(
        id=65,
        name_arabic="الطلاق",
        name_translit="At-Talaq",
        name_translation="The Divorce",
        revelation_type="medinan",
        ayah_count=12,
        order_number=65,
    ),
    SurahModel(
        id=66,
        name_arabic="التحريم",
        name_translit="At-Tahrim",
        name_translation="The Prohibition",
        revelation_type="medinan",
        ayah_count=12,
        order_number=66,
    ),
    SurahModel(
        id=67,
        name_arabic="الملك",
        name_translit="Al-Mulk",
        name_translation="The Sovereignty",
        revelation_type="meccan",
        ayah_count=30,
        order_number=67,
    ),
    SurahModel(
        id=68,
        name_arabic="القلم",
        name_translit="Al-Qalam",
        name_translation="The Pen",
        revelation_type="meccan",
        ayah_count=52,
        order_number=68,
    ),
    SurahModel(
        id=69,
        name_arabic="الحاقة",
        name_translit="Al-Haqqah",
        name_translation="The Reality",
        revelation_type="meccan",
        ayah_count=52,
        order_number=69,
    ),
    SurahModel(
        id=70,
        name_arabic="المعارج",
        name_translit="Al-Maarij",
        name_translation="The Ascending Stairways",
        revelation_type="meccan",
        ayah_count=44,
        order_number=70,
    ),
    SurahModel(
        id=71,
        name_arabic="نوح",
        name_translit="Nuh",
        name_translation="Noah",
        revelation_type="meccan",
        ayah_count=28,
        order_number=71,
    ),
    SurahModel(
        id=72,
        name_arabic="الجن",
        name_translit="Al-Jinn",
        name_translation="The Jinn",
        revelation_type="meccan",
        ayah_count=28,
        order_number=72,
    ),
    SurahModel(
        id=73,
        name_arabic="المزمل",
        name_translit="Al-Muzzammil",
        name_translation="The Enshrouded One",
        revelation_type="meccan",
        ayah_count=20,
        order_number=73,
    ),
    SurahModel(
        id=74,
        name_arabic="المدثر",
        name_translit="Al-Muddaththir",
        name_translation="The Cloaked One",
        revelation_type="meccan",
        ayah_count=56,
        order_number=74,
    ),
    SurahModel(
        id=75,
        name_arabic="القيامة",
        name_translit="Al-Qiyamah",
        name_translation="The Resurrection",
        revelation_type="meccan",
        ayah_count=40,
        order_number=75,
    ),
    SurahModel(
        id=76,
        name_arabic="الإنسان",
        name_translit="Al-Insan",
        name_translation="Man",
        revelation_type="medinan",
        ayah_count=31,
        order_number=76,
    ),
    SurahModel(
        id=77,
        name_arabic="المرسلات",
        name_translit="Al-Mursalat",
        name_translation="The Emissaries",
        revelation_type="meccan",
        ayah_count=50,
        order_number=77,
    ),
    SurahModel(
        id=78,
        name_arabic="النبأ",
        name_translit="An-Naba",
        name_translation="The Tidings",
        revelation_type="meccan",
        ayah_count=40,
        order_number=78,
    ),
    SurahModel(
        id=79,
        name_arabic="النازعات",
        name_translit="An-Naziat",
        name_translation="Those Who Drag Forth",
        revelation_type="meccan",
        ayah_count=46,
        order_number=79,
    ),
    SurahModel(
        id=80,
        name_arabic="عبس",
        name_translit="Abasa",
        name_translation="He Frowned",
        revelation_type="meccan",
        ayah_count=42,
        order_number=80,
    ),
    SurahModel(
        id=81,
        name_arabic="التكوير",
        name_translit="At-Takwir",
        name_translation="The Overthrowing",
        revelation_type="meccan",
        ayah_count=29,
        order_number=81,
    ),
    SurahModel(
        id=82,
        name_arabic="الانفطار",
        name_translit="Al-Infitar",
        name_translation="The Cleaving",
        revelation_type="meccan",
        ayah_count=19,
        order_number=82,
    ),
    SurahModel(
        id=83,
        name_arabic="المطففين",
        name_translit="Al-Mutaffifin",
        name_translation="The Defrauding",
        revelation_type="meccan",
        ayah_count=36,
        order_number=83,
    ),
    SurahModel(
        id=84,
        name_arabic="الانشقاق",
        name_translit="Al-Inshiqaq",
        name_translation="The Sundering",
        revelation_type="meccan",
        ayah_count=25,
        order_number=84,
    ),
    SurahModel(
        id=85,
        name_arabic="البروج",
        name_translit="Al-Buruj",
        name_translation="The Mansions of the Stars",
        revelation_type="meccan",
        ayah_count=22,
        order_number=85,
    ),
    SurahModel(
        id=86,
        name_arabic="الطارق",
        name_translit="At-Tariq",
        name_translation="The Nightcomer",
        revelation_type="meccan",
        ayah_count=17,
        order_number=86,
    ),
    SurahModel(
        id=87,
        name_arabic="الأعلى",
        name_translit="Al-Ala",
        name_translation="The Most High",
        revelation_type="meccan",
        ayah_count=19,
        order_number=87,
    ),
    SurahModel(
        id=88,
        name_arabic="الغاشية",
        name_translit="Al-Ghashiyah",
        name_translation="The Overwhelming",
        revelation_type="meccan",
        ayah_count=26,
        order_number=88,
    ),
    SurahModel(
        id=89,
        name_arabic="الفجر",
        name_translit="Al-Fajr",
        name_translation="The Dawn",
        revelation_type="meccan",
        ayah_count=30,
        order_number=89,
    ),
    SurahModel(
        id=90,
        name_arabic="البلد",
        name_translit="Al-Balad",
        name_translation="The City",
        revelation_type="meccan",
        ayah_count=20,
        order_number=90,
    ),
    SurahModel(
        id=91,
        name_arabic="الشمس",
        name_translit="Ash-Shams",
        name_translation="The Sun",
        revelation_type="meccan",
        ayah_count=15,
        order_number=91,
    ),
    SurahModel(
        id=92,
        name_arabic="الليل",
        name_translit="Al-Layl",
        name_translation="The Night",
        revelation_type="meccan",
        ayah_count=21,
        order_number=92,
    ),
    SurahModel(
        id=93,
        name_arabic="الضحى",
        name_translit="Ad-Duha",
        name_translation="The Morning Hours",
        revelation_type="meccan",
        ayah_count=11,
        order_number=93,
    ),
    SurahModel(
        id=94,
        name_arabic="الشرح",
        name_translit="Ash-Sharh",
        name_translation="The Relief",
        revelation_type="meccan",
        ayah_count=8,
        order_number=94,
    ),
    SurahModel(
        id=95,
        name_arabic="التين",
        name_translit="At-Tin",
        name_translation="The Fig",
        revelation_type="meccan",
        ayah_count=8,
        order_number=95,
    ),
    SurahModel(
        id=96,
        name_arabic="العلق",
        name_translit="Al-Alaq",
        name_translation="The Clot",
        revelation_type="meccan",
        ayah_count=19,
        order_number=96,
    ),
    SurahModel(
        id=97,
        name_arabic="القدر",
        name_translit="Al-Qadr",
        name_translation="The Power",
        revelation_type="meccan",
        ayah_count=5,
        order_number=97,
    ),
    SurahModel(
        id=98,
        name_arabic="البينة",
        name_translit="Al-Bayyinah",
        name_translation="The Clear Proof",
        revelation_type="medinan",
        ayah_count=8,
        order_number=98,
    ),
    SurahModel(
        id=99,
        name_arabic="الزلزلة",
        name_translit="Az-Zalzalah",
        name_translation="The Earthquake",
        revelation_type="medinan",
        ayah_count=8,
        order_number=99,
    ),
    SurahModel(
        id=100,
        name_arabic="العاديات",
        name_translit="Al-Adiyat",
        name_translation="The Courser",
        revelation_type="meccan",
        ayah_count=11,
        order_number=100,
    ),
    SurahModel(
        id=101,
        name_arabic="القارعة",
        name_translit="Al-Qariah",
        name_translation="The Calamity",
        revelation_type="meccan",
        ayah_count=11,
        order_number=101,
    ),
    SurahModel(
        id=102,
        name_arabic="التكاثر",
        name_translit="At-Takathur",
        name_translation="The Rivalry in World Increase",
        revelation_type="meccan",
        ayah_count=8,
        order_number=102,
    ),
    SurahModel(
        id=103,
        name_arabic="العصر",
        name_translit="Al-Asr",
        name_translation="The Declining Day",
        revelation_type="meccan",
        ayah_count=3,
        order_number=103,
    ),
    SurahModel(
        id=104,
        name_arabic="الهمزة",
        name_translit="Al-Humazah",
        name_translation="The Traducer",
        revelation_type="meccan",
        ayah_count=9,
        order_number=104,
    ),
    SurahModel(
        id=105,
        name_arabic="الفيل",
        name_translit="Al-Fil",
        name_translation="The Elephant",
        revelation_type="meccan",
        ayah_count=5,
        order_number=105,
    ),
    SurahModel(
        id=106,
        name_arabic="قريش",
        name_translit="Quraysh",
        name_translation="Quraysh",
        revelation_type="meccan",
        ayah_count=4,
        order_number=106,
    ),
    SurahModel(
        id=107,
        name_arabic="الماعون",
        name_translit="Al-Maun",
        name_translation="The Small Kindnesses",
        revelation_type="meccan",
        ayah_count=7,
        order_number=107,
    ),
    SurahModel(
        id=108,
        name_arabic="الكوثر",
        name_translit="Al-Kawthar",
        name_translation="The Abundance",
        revelation_type="meccan",
        ayah_count=3,
        order_number=108,
    ),
    SurahModel(
        id=109,
        name_arabic="الكافرون",
        name_translit="Al-Kafirun",
        name_translation="The Disbelievers",
        revelation_type="meccan",
        ayah_count=6,
        order_number=109,
    ),
    SurahModel(
        id=110,
        name_arabic="النصر",
        name_translit="An-Nasr",
        name_translation="The Divine Support",
        revelation_type="medinan",
        ayah_count=3,
        order_number=110,
    ),
    SurahModel(
        id=111,
        name_arabic="المسد",
        name_translit="Al-Masad",
        name_translation="The Palm Fiber",
        revelation_type="meccan",
        ayah_count=5,
        order_number=111,
    ),
    SurahModel(
        id=112,
        name_arabic="الإخلاص",
        name_translit="Al-Ikhlas",
        name_translation="Sincerity",
        revelation_type="meccan",
        ayah_count=4,
        order_number=112,
    ),
    SurahModel(
        id=113,
        name_arabic="الفلق",
        name_translit="Al-Falaq",
        name_translation="The Daybreak",
        revelation_type="meccan",
        ayah_count=5,
        order_number=113,
    ),
    SurahModel(
        id=114,
        name_arabic="الناس",
        name_translit="An-Nas",
        name_translation="Mankind",
        revelation_type="meccan",
        ayah_count=6,
        order_number=114,
    ),
]


def get_all_surahs() -> list[SurahModel]:
    return SURAHS
